import { i18n } from '../../i18n';

export const createDeformations = () => {
    return [
        {
            name: i18n.$tsl('无变形'),
            type: 'none',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 0,
                    min: 0,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-09b6.png',
        },
        {
            name: i18n.$tsl('水平弧形路径'),
            type: 'horizontalCurvedRotate-byWord',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20200117-154342-ab59.png',
        },
        {
            name: i18n.$tsl('椭圆形'),
            type: 'ellipse-byWord',
            attrs: [
                {
                    name: i18n.$tsl('大小'),
                    value: 40,
                    min: 0,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('起始角度'),
                    value: 0,
                    min: -180,
                    max: 180,
                    start: 0,
                    suffix: '°',
                },
                {
                    name: i18n.$tsl('长度'),
                    value: 360,
                    min: 0,
                    max: 360,
                    start: 0,
                    suffix: '°',
                },
                {
                    name: i18n.$tsl('离心率'),
                    value: 0,
                    min: 0,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
            ],
            isFollowTangent: true,
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20200117-154342-ebb7.png',
        },
        {
            name: i18n.$tsl('三角形'),
            type: 'triangle-byWord',
            attrs: [
                {
                    name: i18n.$tsl('大小'),
                    value: 50,
                    min: 0,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('边数'),
                    value: 3,
                    min: 3,
                    max: 10,
                    start: 0,
                },
                {
                    name: i18n.$tsl('起始位置'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
                {
                    name: i18n.$tsl('长度'),
                    value: 100,
                    min: 0,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
            ],
            isFollowTangent: true,
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20200117-154342-b3d6.png',
        },
        {
            name: i18n.$tsl('方形'),
            type: 'rectangular-byWord',
            attrs: [
                {
                    name: i18n.$tsl('大小'),
                    value: 50,
                    min: 0,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('长宽比'),
                    value: 100,
                    min: 20,
                    max: 500,
                    start: 0,
                    suffix: '%',
                },
                {
                    name: i18n.$tsl('起始位置'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
                {
                    name: i18n.$tsl('长度'),
                    value: 100,
                    min: 0,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
            ],
            isFollowTangent: true,
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20200117-154342-7bae.png',
        },
        {
            name: i18n.$tsl('五边形'),
            type: 'pentagon-byWord',
            attrs: [
                {
                    name: i18n.$tsl('大小'),
                    value: 50,
                    min: 0,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('边数'),
                    value: 5,
                    min: 3,
                    max: 10,
                    start: 0,
                },
                {
                    name: i18n.$tsl('起始位置'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
                {
                    name: i18n.$tsl('长度'),
                    value: 100,
                    min: 0,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
            ],
            isFollowTangent: true,
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20200117-154342-9df9.png',
        },
        {
            name: i18n.$tsl('心形'),
            type: 'heart-byWord',
            attrs: [
                {
                    name: i18n.$tsl('大小'),
                    value: 36,
                    min: 0,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('起始位置'),
                    value: -10,
                    min: -100,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
                {
                    name: i18n.$tsl('长度'),
                    value: 100,
                    min: 0,
                    max: 100,
                    start: 0,
                    suffix: '%',
                },
            ],
            isFollowTangent: true,
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20200117-154342-7b3a.png',
        },
        {
            name: i18n.$tsl('拱形'),
            type: 'archCurve',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-38cc.png',
        },
        {
            name: i18n.$tsl('弯曲'),
            type: 'bend',
            attrs: [
                {
                    name: i18n.$tsl('角度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20200117-161831-75ed.png',
        },
        {
            name: i18n.$tsl('内凹'),
            type: 'concaveCurve',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: 0,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-9734.png',
        },
        {
            name: i18n.$tsl('上拱形'),
            type: 'upperArchCurve',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-3796.png',
        },
        {
            name: i18n.$tsl('下拱形'),
            type: 'lowerArchCurve',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-c78e.png',
        },
        {
            name: i18n.$tsl('凸出'),
            type: 'bulbCurve',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: 0,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-40cc.png',
        },
        {
            name: i18n.$tsl('斜切'),
            type: 'skew',
            attrs: [
                {
                    name: i18n.$tsl('左右斜切'),
                    value: 30,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('上下斜切'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-81b6.png',
        },
        {
            name: i18n.$tsl('旗形'),
            type: 'flagCurve',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-a242.png',
        },
        {
            name: i18n.$tsl('梯形'),
            type: 'trapezoid',
            attrs: [
                {
                    name: i18n.$tsl('梯形强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-db3c.png',
        },
        {
            name: i18n.$tsl('下梯形'),
            type: 'lowerTrapezoid',
            attrs: [
                {
                    name: i18n.$tsl('梯形强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-1d1a.png',
        },
        {
            name: i18n.$tsl('上梯形'),
            type: 'topTrapezoid',
            attrs: [
                {
                    name: i18n.$tsl('梯形强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-8111.png',
        },
        {
            name: i18n.$tsl('横向梯形'),
            type: 'horizontalTrapezoid',
            attrs: [
                {
                    name: i18n.$tsl('梯形强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-69de.png',
        },
        {
            name: i18n.$tsl('折角'),
            type: 'bevel',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-2fcb.png',
        },
        {
            name: i18n.$tsl('上屋顶'),
            type: 'upperRoof',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-110f.png',
        },
        {
            name: i18n.$tsl('下屋顶'),
            type: 'lowerRoof',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-7ee1.png',
        },
        {
            name: i18n.$tsl('折角凸出'),
            type: 'angledProjection',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: 0,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-22e4.png',
        },
        {
            name: i18n.$tsl('折角内凹'),
            type: 'foldedCorner',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: 0,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('相对高度'),
                    value: 0,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-7709.png',
        },
        {
            name: i18n.$tsl('横向弯曲'),
            type: 'bendVertical',
            attrs: [
                {
                    name: i18n.$tsl('角度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20200117-154342-b096.png',
        },
        {
            name: i18n.$tsl('横向拉伸'),
            type: 'lateralStretching',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-d5f7.png',
        },
        {
            name: i18n.$tsl('纵向拉伸'),
            type: 'verticalStretching',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-21ab.png',
        },
        {
            name: i18n.$tsl('错落'),
            type: 'patchwork-byWord',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-696e.png',
        },
        {
            name: i18n.$tsl('阶梯'),
            type: 'step-byWord',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-d682.png',
        },
        {
            name: i18n.$tsl('拱形'),
            type: 'arch2-byWord',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-4962.png',
        },
        {
            name: i18n.$tsl('波形'),
            type: 'wave-byWord',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-576b.png',
        },
        {
            name: i18n.$tsl('阶梯远近'),
            type: 'stepFarAndNear-byWord',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-671a.png',
        },
        {
            name: i18n.$tsl('拱形远近'),
            type: 'archFarAndNear-byWord',
            attrs: [
                {
                    name: i18n.$tsl('强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-e69a.png',
        },
        {
            name: i18n.$tsl('水平旋转'),
            type: 'horizontalRotate-byWord',
            attrs: [
                {
                    name: i18n.$tsl('角度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                    suffix: '°',
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191014-163045-05dd.png',
        },
        {
            name: i18n.$tsl('逐字分散'),
            type: 'arbitraryOffsetRotate-byWord',
            attrs: [
                {
                    name: i18n.$tsl('偏移强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
                {
                    name: i18n.$tsl('旋转强度'),
                    value: 50,
                    min: -100,
                    max: 100,
                    start: 0,
                },
            ],
            url: 'https://st-gdx.dancf.com/gaodingx/210/design/three/20191016-203319-a505.png',
        },
    ];
};
