export default {
    type: 'threeText',
    width: 419.6304975086487,
    height: 467.4851256880163,
    left: 210.84898372717376,
    top: -15.806265302265814,
    transform: {
        a: 1,
        b: 0,
        c: 0,
        d: 1,
        tx: 0,
        ty: 0,
    },
    resize: 1,
    filter: {
        hueRotate: 0,
        saturate: 0,
        brightness: 0,
        gaussianBlur: 0,
    },
    rotate3d: [0.4400000000000002, -0.5800000000000001, 0],
    fontFamily: 'Reeji - CloudYuanCu - GB - Regular',
    layers: [
        {
            frontMaterials: {
                metalRoughness: '#00ffff',
                normal: '#807fff',
                albedo: {
                    type: 1,
                    image: 'https://st0.dancf.com/csc/147/material-three-textures/0/20190606-150053-46e8.jpg',
                    color: '#ace030ff',
                    gradient: {
                        angle: 0,
                        stops: [
                            {
                                color: '#ffffffff',
                                offset: 0,
                            },
                            {
                                color: '#000000ff',
                                offset: 1,
                            },
                        ],
                        direction: [1, 0, 0],
                        type: 0,
                        face: 0,
                    },
                    texRotateAngle: 0,
                    texTranslate: [0, 0],
                },
                metalStrength: 0.4252873563218391,
                roughnessStrength: 0.25287356321839083,
                albedoStrength: 1,
                normalStrength: 0,
                normalDisable: false,
                scale: 1,
            },
            sideMaterials: {
                enable: false,
                metalRoughness: '#00ffff',
                normal: '#807fff',
                albedo: {
                    type: 0,
                    image: '',
                    color: '#0008ffff',
                    gradient: {
                        angle: 0,
                        stops: [
                            {
                                color: '#ffffffff',
                                offset: 0,
                            },
                            {
                                color: '#000000ff',
                                offset: 1,
                            },
                        ],
                        direction: [1, 0, 0],
                        type: 0,
                        face: 0,
                    },
                    texRotateAngle: 0,
                    texTranslate: [0, 0],
                },
                metalStrength: 1,
                roughnessStrength: 1,
                albedoStrength: 1,
                normalStrength: 0,
                normalDisable: false,
                scale: 1,
            },
            bevelMaterials: {
                enable: false,
                metalRoughness: '#00ffff',
                normal: '#807fff',
                albedo: {
                    type: 0,
                    image: '',
                    color: '#ff00ffff',
                    gradient: {
                        angle: 0,
                        stops: [
                            {
                                color: '#ffffffff',
                                offset: 0,
                            },
                            {
                                color: '#000000ff',
                                offset: 1,
                            },
                        ],
                        direction: [1, 0, 0],
                        type: 0,
                        face: 0,
                    },
                    texRotateAngle: 0,
                    texTranslate: [0, 0],
                },
                metalStrength: 1,
                roughnessStrength: 0,
                albedoStrength: 1,
                normalStrength: 2,
                normalDisable: false,
                scale: 1,
            },
            bevelSize: 80,
            bevelThickness: 10,
            bevelSegments: 4,
            bevelType: 'quadEllipse',
            curveSegments: 1,
            extrudeDepth: 40,
            extrudeOffsetX: 0,
            extrudeOffsetY: 0,
            extrudeScale: 0,
            shadingSmoothAngle: 50,
            extrudeScaleX: 0,
            extrudeScaleY: 0,
            expand: 0,
        },
    ],
    pointLights: [],
    viewAngle: 30,
    environment: {
        enable: true,
        maps: ['https://st-gdx.dancf.com/gaodingx/17/design/three/20190530-210836-623d.jpg'],
        strength: 1.031914893617021,
        rotate3d: [0, 0, 0],
    },
    fontSize: 200,
    content: 'a',
    lineHeight: 1,
    letterSpacing: 0,
    // 'left' 'center' 'right'
    textAlign: 'center',
    // 'horizontal-tb' 'vertical-rl','vertical-lr'
    writingMode: 'horizontal-tb',
    isOrtho: false,
    shadow: {
        enable: false,
        type: 'projection-2d', // 2d 普通投影
        blur: 10,
        color: '#000000ff',
        offset: 0,
        opacity: 1, // 暂时没用
        angle: 0,
        isBindRotate: false,
        offsetRatio: 1,
    },
    deformation: {
        // enable: true,
        type: 'none',
        intensity: 0,
        intensity1: 0,
        extrudeScaleX: 0, // 挤出面 x 方向缩放
        extrudeScaleY: 0, // 挤出面 y 方向缩放
    },
    // 逐字偏移
    warpByWord: {
        enable: false,
        intensity: 0,
        intensity1: 0,
        randNum: 1000,
        pattern: '1',
        offsetX: 0,
    },
    modelCube: [-0.7524567801774561, 0.7734723016721756, -0.9387875937860526, 0.7611583178067339],
    centerRatioX: -0.49311386035409793,
    centerRatioY: -0.44775443301814033,
    imageUrl: '',
    $showCoordinate: false,
    isMesh: false,
    hemiLight: {
        enable: false,
        color: '#ffffff',
        dir: [0, 0, 1],
        strength: 1,
    },
    isFloodLightOff: false,
};
